[UNDERTOW-2100][UNDERTOW-2052] Upgrading Jastow Components
undertow-io/jastow pull request #59
Opened 2022-06-03 13:41 UTC by ropalka

https://issues.redhat.com/browse/UNDERTOW-2052 Upgrading Servlet API to 6.0.0
https://issues.redhat.com/browse/UNDERTOW-2100 Upgrading JSP API to 3.1.0

2022-06-03 13:50 UTC, fl4via requested changes
There is just a typo to be fixed, and some questions about dependencies to be answered.

2022-06-03 13:50 UTC, fl4via commented on test/org/apache/el/TestELInJsp.java
> +        // jakarrta.servlet
just a small typo

2022-06-03 13:50 UTC, fl4via commented on pom.xml
> +        <!-- test dependencies -->
just a small consideration, are all these test dependencies? If so, shouldn't they have the scope test?

2022-06-03 13:50 UTC, fl4via commented on pom.xml
> +        <!-- provided dependencies -->
See comment below about test dependencies. I'm just wondering if any of these dependencies should have a provided scope or not? I don't think it would have an impact in WF because probably WF already depends on all of them anyway, but it is important to double check this to make sure, and to consider if any of these dependencies should be marked as provided  or not, and then consider whether the "provided dependencies" comment applies.

2022-06-03 17:01 UTC, ropalka commented on test/org/apache/el/TestELInJsp.java
> +        // jakarrta.servlet
Fixed

2022-06-03 17:02 UTC, ropalka commented on pom.xml
> +        <!-- test dependencies -->
I'm little bit confused with this comment. AFAICS all test dependencies have scope test in pom.xml @fl4via

2022-06-03 17:03 UTC, ropalka commented on pom.xml
> +        <!-- provided dependencies -->
There are two different types of dependencies. undertow-core and undertow-servlet artifacts are there in both provided and test scope. Please these artifacts with test scope are using different classifier in order to depend on test jar artifacts (to reuse test utilities there).

2022-06-07 13:39 UTC, fl4via approved these changes

2022-06-07 13:40 UTC, fl4via commented
You're right about the dependencies, @ropalka , I just hadn't noticed the scope in the lines above.

2022-06-07 13:42 UTC, merged